version 2:


models:
  - name: weather_summary
    description: "Daily summary of weather aggregated by city"
    columns:
      - name: day
        tests: [not_null]
      - name: city
        tests: [not_null]
      - name: avg_temp
        description: "Average temperature for the day"
      - name: nb_points
        description: "Number of hourly data points aggregated"